// api/transcript-backup.js
// Backup transcript service using direct YouTube timedtext API fetch
// This is a SEPARATE endpoint - does NOT use youtube-caption-extractor
// Uses raw fetch to YouTube's internal caption API

// CORS headers
const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'Content-Type, Authorization',
  'Access-Control-Allow-Methods': 'POST, OPTIONS'
};

// Fetch video page and extract caption track info
async function getCaptionTracksFromVideoPage(videoId) {
  console.log(`🔍 Fetching video page for caption tracks...`);

  const videoUrl = `https://www.youtube.com/watch?v=${videoId}`;
  const response = await fetch(videoUrl, {
    headers: {
      'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
      'Accept-Language': 'en-US,en;q=0.9'
    }
  });

  if (!response.ok) {
    throw new Error(`Failed to fetch video page: ${response.status}`);
  }

  const html = await response.text();

  // Extract captionTracks from the page
  const captionRegex = /"captionTracks":\s*(\[.*?\])/;
  const match = html.match(captionRegex);

  if (!match) {
    // Try alternative pattern
    const altRegex = /captionTracks":\s*(\[[\s\S]*?\])\s*,\s*"/;
    const altMatch = html.match(altRegex);
    if (!altMatch) {
      throw new Error('No caption tracks found in video page');
    }
    return JSON.parse(altMatch[1]);
  }

  return JSON.parse(match[1]);
}

// Fetch captions from a track URL
async function fetchCaptionsFromTrack(trackUrl) {
  console.log(`📥 Fetching captions from track URL...`);

  // Request JSON format by appending fmt=json3
  const jsonUrl = trackUrl.includes('?')
    ? `${trackUrl}&fmt=json3`
    : `${trackUrl}?fmt=json3`;

  const response = await fetch(jsonUrl, {
    headers: {
      'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
    }
  });

  if (!response.ok) {
    throw new Error(`Failed to fetch captions: ${response.status}`);
  }

  const data = await response.json();
  return data;
}

// Parse JSON3 format captions
function parseJson3Captions(data) {
  if (!data.events) {
    throw new Error('No caption events found');
  }

  const segments = [];

  for (const event of data.events) {
    if (event.segs) {
      const text = event.segs.map(seg => seg.utf8 || '').join('');
      if (text.trim()) {
        segments.push({
          text: text.trim(),
          start: event.tStartMs / 1000,
          duration: (event.dDurationMs || 0) / 1000
        });
      }
    }
  }

  return segments;
}

// Main extraction function
async function extractTranscriptDirect(videoId, lang = 'en') {
  console.log(`🚀 Starting direct transcript extraction for: ${videoId}`);

  // Get caption tracks from video page
  const tracks = await getCaptionTracksFromVideoPage(videoId);

  if (!tracks || tracks.length === 0) {
    throw new Error('No caption tracks available');
  }

  console.log(`📋 Found ${tracks.length} caption track(s)`);

  // Find the requested language track or fallback
  let selectedTrack = tracks.find(t => t.languageCode === lang);

  // If requested language not found, try English variants
  if (!selectedTrack && lang === 'en') {
    selectedTrack = tracks.find(t =>
      t.languageCode === 'en-US' ||
      t.languageCode === 'en-GB' ||
      t.languageCode.startsWith('en')
    );
  }

  // If still not found, use first available
  if (!selectedTrack) {
    selectedTrack = tracks[0];
    console.log(`⚠️ Requested language '${lang}' not found, using '${selectedTrack.languageCode}'`);
  }

  console.log(`🎯 Using track: ${selectedTrack.languageCode} (${selectedTrack.name?.simpleText || 'auto-generated'})`);

  // Fetch the actual captions
  const captionData = await fetchCaptionsFromTrack(selectedTrack.baseUrl);

  // Parse the captions
  const segments = parseJson3Captions(captionData);

  if (segments.length === 0) {
    throw new Error('No transcript segments extracted');
  }

  // Combine into full transcript
  const transcript = segments.map(s => s.text).join(' ');

  return {
    transcript,
    segments: segments.length,
    language: selectedTrack.languageCode,
    isAutoGenerated: selectedTrack.kind === 'asr',
    availableTracks: tracks.map(t => ({
      language: t.languageCode,
      name: t.name?.simpleText || 'Unknown'
    }))
  };
}

// Main API handler
export default async function handler(req, res) {
  // Handle CORS preflight
  if (req.method === 'OPTIONS') {
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');
    res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
    res.status(200).end();
    return;
  }

  // Only allow POST requests
  if (req.method !== 'POST') {
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.status(405).json({ error: 'Method not allowed. Use POST.' });
    return;
  }

  try {
    console.log('🔄 Backup Transcript Service (direct fetch) called');

    const { videoId, lang = 'en' } = req.body;

    if (!videoId) {
      res.setHeader('Access-Control-Allow-Origin', '*');
      res.status(400).json({ error: 'Missing required parameter: videoId' });
      return;
    }

    console.log(`🎬 Processing video: ${videoId}`);

    // Extract transcript using direct method
    const result = await extractTranscriptDirect(videoId, lang);

    console.log(`✅ Transcript extracted: ${result.transcript.length} characters`);

    res.setHeader('Access-Control-Allow-Origin', '*');
    res.status(200).json({
      success: true,
      data: {
        transcript: result.transcript,
        segments: result.segments,
        language: result.language,
        source: 'youtube-direct-fetch',
        isAutoGenerated: result.isAutoGenerated,
        videoId: videoId,
        availableLanguages: result.availableTracks
      },
      message: 'Transcript extracted via backup service (direct fetch)'
    });

  } catch (error) {
    console.error('❌ Backup service error:', error.message);

    res.setHeader('Access-Control-Allow-Origin', '*');
    res.status(500).json({
      success: false,
      error: error.message,
      message: 'Backup transcript extraction failed',
      hint: 'This video may not have captions available.'
    });
  }
}
